# Generated by Django 4.1.3 on 2023-02-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_flick_delete_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flick',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
